USE DB_A05644_socialcare;

DELETE FROM TAB__MATERIAL;
DBCC CHECKIDENT ('TAB__MATERIAL', RESEED, 0);

DELETE FROM TAB_CID;
DBCC CHECKIDENT ('TAB_CID', RESEED, 0);

DELETE FROM TAB_DIAGNOSTICO;
DBCC CHECKIDENT ('TAB_DIAGNOSTICO', RESEED, 0);

DELETE FROM TAB_FORM;
DBCC CHECKIDENT ('TAB_FORM', RESEED, 0);

DELETE FROM TAB_FORM_MAT;
DBCC CHECKIDENT ('TAB_FORM_MAT', RESEED, 0);

DELETE FROM	TAB_FORM_PROC_ENF;
DBCC CHECKIDENT ('TAB_FORM_PROC_ENF', RESEED, 0);

DELETE FROM TAB_VISITA;
DBCC CHECKIDENT ('TAB_VISITA', RESEED, 0);

DELETE FROM TAB_PACIENTE;
DBCC CHECKIDENT ('TAB_PACIENTE', RESEED, 0);

DELETE FROM TAB_PROC_ENF;
DBCC CHECKIDENT ('TAB_PROC_ENF', RESEED, 0);

DELETE FROM TAB_PROCEDIMENTO;
DBCC CHECKIDENT ('TAB_PROCEDIMENTO', RESEED, 0);

DELETE FROM TAB_PROFISSIONAL;
DBCC CHECKIDENT ('TAB_PROFISSIONAL', RESEED, 0);

DELETE FROM TAB_SAIDA;
DBCC CHECKIDENT ('TAB_SAIDA', RESEED, 0);

DELETE FROM TAB_UP;
DBCC CHECKIDENT ('TAB_UP', RESEED, 0);

DELETE FROM TAB_VISITA_PROC;
DBCC CHECKIDENT ('TAB_VISITA_PROC', RESEED, 0);
